CREATE TABLE "account" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" bigint,
	"token_type" varchar(255),
	CONSTRAINT "account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "auth_session" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) DEFAULT '' NOT NULL,
	"email" varchar(255) NOT NULL,
	"finished_registration" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contest" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text PRIMARY KEY NOT NULL,
	"start_date" timestamp with time zone NOT NULL,
	"expected_end_date" timestamp with time zone NOT NULL,
	"end_date" timestamp with time zone,
	"is_ongoing" boolean NOT NULL,
	"system_initial" boolean DEFAULT false NOT NULL,
	CONSTRAINT "contest_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "discipline" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "round_session" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "round_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contestant_id" text NOT NULL,
	"round_id" integer NOT NULL,
	"avg_ms" integer,
	"is_dnf" boolean,
	"is_finished" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "round" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "round_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contest_slug" text NOT NULL,
	"discipline_slug" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scramble" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scramble_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"round_id" integer NOT NULL,
	"position" text NOT NULL,
	"is_extra" boolean GENERATED ALWAYS AS (CASE WHEN position IN ('E1', 'E2') THEN TRUE ELSE FALSE END) STORED NOT NULL,
	"moves" text NOT NULL,
	CONSTRAINT "round_position_unique" UNIQUE("round_id","position")
);
--> statement-breakpoint
CREATE TABLE "solve" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solve_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scramble_id" integer NOT NULL,
	"round_session_id" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"time_ms" integer,
	"is_dnf" boolean NOT NULL,
	"solution" varchar(10000),
	CONSTRAINT "round_session_scramble_unique" UNIQUE("round_session_id","scramble_id")
);
--> statement-breakpoint
CREATE TABLE "user_simulator_settings" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_simulator_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"animation_duration" integer DEFAULT 100 NOT NULL,
	"inspection_voice_alert" text DEFAULT 'Male' NOT NULL,
	"camera_position_theta" integer DEFAULT 0 NOT NULL,
	"camera_position_phi" integer DEFAULT 6 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_session" ADD CONSTRAINT "auth_session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round_session" ADD CONSTRAINT "round_session_contestant_id_user_id_fk" FOREIGN KEY ("contestant_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round_session" ADD CONSTRAINT "round_session_round_id_round_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."round"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round" ADD CONSTRAINT "round_contest_slug_contest_slug_fk" FOREIGN KEY ("contest_slug") REFERENCES "public"."contest"("slug") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round" ADD CONSTRAINT "round_discipline_slug_discipline_slug_fk" FOREIGN KEY ("discipline_slug") REFERENCES "public"."discipline"("slug") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scramble" ADD CONSTRAINT "scramble_round_id_round_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."round"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solve" ADD CONSTRAINT "solve_scramble_id_scramble_id_fk" FOREIGN KEY ("scramble_id") REFERENCES "public"."scramble"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solve" ADD CONSTRAINT "solve_round_session_id_round_session_id_fk" FOREIGN KEY ("round_session_id") REFERENCES "public"."round_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_simulator_settings" ADD CONSTRAINT "user_simulator_settings_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "auth_session" USING btree ("user_id");