CREATE TYPE "public"."scramblePosition" AS ENUM('1', '2', '3', '4', '5', 'E1', 'E2');--> statement-breakpoint
CREATE TABLE "scramble" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scramble_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contestDisciplineId" integer NOT NULL,
	"position" "scramblePosition" NOT NULL,
	"isExtra" boolean GENERATED ALWAYS AS (CASE WHEN position IN ('E1', 'E2') THEN TRUE ELSE FALSE END) STORED NOT NULL,
	"moves" text
);
--> statement-breakpoint
ALTER TABLE "scramble" ADD CONSTRAINT "scramble_contestDisciplineId_contest_discipline_id_fk" FOREIGN KEY ("contestDisciplineId") REFERENCES "public"."contest_discipline"("id") ON DELETE cascade ON UPDATE no action;