CREATE TABLE "roundSession" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roundSession_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"avgMs" integer,
	"isDnf" boolean,
	"isFinished" boolean NOT NULL,
	"contestDisciplineId" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "roundSession" ADD CONSTRAINT "roundSession_contestDisciplineId_contest_discipline_id_fk" FOREIGN KEY ("contestDisciplineId") REFERENCES "public"."contest_discipline"("id") ON DELETE cascade ON UPDATE no action;