CREATE TABLE "user_simulator_settings" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_simulator_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"animationDuration" integer DEFAULT 10 NOT NULL,
	"inspectionVoiceAlert" text DEFAULT 'Male',
	"cameraPositionTheta" integer DEFAULT 0 NOT NULL,
	"cameraPositionPhi" integer DEFAULT 6 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "post" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "post" CASCADE;--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "simulator_settings_id" integer;--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_simulator_settings_id_user_simulator_settings_id_fk" FOREIGN KEY ("simulator_settings_id") REFERENCES "public"."user_simulator_settings"("id") ON DELETE no action ON UPDATE no action;