CREATE TABLE "contest" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"startDate" timestamp with time zone NOT NULL,
	"endDate" timestamp with time zone,
	"isOngoing" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discipline" (
	"name" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contest_discipline" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contest_discipline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contestId" integer NOT NULL,
	"disciplineName" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "contest_discipline" ADD CONSTRAINT "contest_discipline_contestId_contest_id_fk" FOREIGN KEY ("contestId") REFERENCES "public"."contest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contest_discipline" ADD CONSTRAINT "contest_discipline_disciplineName_discipline_name_fk" FOREIGN KEY ("disciplineName") REFERENCES "public"."discipline"("name") ON DELETE no action ON UPDATE no action;