CREATE TYPE "public"."solveState" AS ENUM('pending', 'submitted', 'changed_to_extra');--> statement-breakpoint
CREATE TABLE "solve" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solve_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scrambleId" integer NOT NULL,
	"roundSessionId" integer NOT NULL,
	"state" "solveState" DEFAULT 'pending' NOT NULL,
	"timeMs" integer,
	"isDnf" boolean NOT NULL,
	"reconstruction" varchar(10000)
);
--> statement-breakpoint
ALTER TABLE "solve" ADD CONSTRAINT "solve_scrambleId_scramble_id_fk" FOREIGN KEY ("scrambleId") REFERENCES "public"."scramble"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solve" ADD CONSTRAINT "solve_roundSessionId_roundSession_id_fk" FOREIGN KEY ("roundSessionId") REFERENCES "public"."roundSession"("id") ON DELETE cascade ON UPDATE no action;