CREATE TABLE "user_simulator_settings" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_simulator_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"animationDuration" integer DEFAULT 10 NOT NULL,
	"inspectionVoiceAlert" text DEFAULT 'Male',
	"cameraPositionTheta" integer DEFAULT 0 NOT NULL,
	"cameraPositionPhi" integer DEFAULT 6 NOT NULL
);
--> statement-breakpoint
DROP TABLE "post" CASCADE;--> statement-breakpoint
ALTER TABLE "user_simulator_settings" ADD CONSTRAINT "user_simulator_settings_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;