name: CI

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  push:
    branches: [main, dev]
  workflow_dispatch:
  
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      - name: Create next-env.d.ts
        run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > src/next-env.d.ts

      - name: Typecheck
        run: bun run type:check

      - name: Format check
        run: bun run format:check

      - name: Lint check
        run: bun run lint:check
