name: Close the ongoing contest and publish a new one

on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:


jobs:
  post-request:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: curl
      run: |
        curl --fail -X POST \
          -H "Authorization: Bearer ${{ secrets.CONTEST_CREATION_WEBHOOK_SECRET }}" \
          ${{ vars.GH_CONTEST_CREATION_WEBHOOK_URL }}
