name: Close the ongoing contest and publish a new one

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:


jobs:
  post-request:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: curl
      uses: sozo-design/curl@v1.0.2
      with:
        args: |
          -X POST ${{ vars.GH_CONTEST_CREATION_WEBHOOK_URL }} \
          -H "Authorization: Bearer ${{ secrets.CONTEST_CREATION_WEBHOOK_SECRET }}" \
